services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    env_file: .env
    environment:
      QDRANT_HOST: qdrant
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3

  frontend:
    build: ./frontend
    ports:
      - "3002:80"
    depends_on:
      - backend
