# Generated by Django 5.2.12 on 2026-06-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.CharField(max_length=120),
        ),
    ]
