# Generated by Django 5.2.12 on 2026-06-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aka', '0003_seed_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('ai', 'AI'), ('blockchain', 'Blockchain'), ('defi', 'DeFi'), ('cefi', 'CeFi')], max_length=30, unique=True),
        ),
    ]
