# Generated by Django 5.2.12 on 2026-06-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aka', '0005_remove_legacy_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_type',
        ),
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='department',
            name='type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='departmentmembership',
            name='role',
            field=models.CharField(choices=[('lead', 'Lead'), ('contributor', 'Contributor'), ('viewer', 'Viewer')], default='contributor', max_length=20),
        ),
        migrations.AlterField(
            model_name='departmentmembership',
            name='sensitivity_ceiling',
            field=models.CharField(choices=[('open', 'Open'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('confidential', 'Confidential')], default='internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='sensitivity',
            field=models.CharField(choices=[('open', 'Open'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('confidential', 'Confidential')], default='internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='informationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('request_received', 'Request Received'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('access_granted', 'Access Granted')], default='request_received', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='org_role',
            field=models.CharField(choices=[('member', 'Member'), ('super_admin', 'Super Admin')], default='member', max_length=20),
        ),
    ]
