# Generated by Django 5.2.12 on 2026-06-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aka', '0006_remove_department_department_type_department_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='mime_type',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
