# Generated by Django 5.2.12 on 2026-06-18 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aka', '0007_document_file_size_document_mime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationrequest',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='information_requests', to='aka.document'),
        ),
    ]
