# Generated by Django 5.2.15 on 2026-06-19 07:12

from django.db import migrations


def grandfather_existing_users(apps, schema_editor):
    """Existing accounts predate the approval workflow, so mark them all
    active/approved to avoid locking anyone out. The seed command then assigns
    precise roles. New registrations explicitly set their own status."""
    User = apps.get_model("aka", "User")
    User.objects.update(approved=True, status="active")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('aka', '0009_user_approved_user_approved_at_user_approved_by_and_more'),
    ]

    operations = [
        migrations.RunPython(grandfather_existing_users, noop),
    ]
